# Generated by Django 5.2.7 on 2026-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_balance_profile_blocked_profile_image_and_more'),
    ]

    operations = [
        # Remove old reset_id field
        migrations.RemoveField(
            model_name='passwordreset',
            name='reset_id',
        ),
        # Add new activation_code field
        migrations.AddField(
            model_name='passwordreset',
            name='activation_code',
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="6-digit activation code sent to user's email",
                max_length=6,
                unique=True,
                default='000000',  # Temporary default
            ),
            preserve_default=False,
        ),
    ]
