# Generated by Django 6.0 on 2026-01-11 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260109_1938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancetransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'ordering': ['-created_when']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Egypt', help_text='Country of residence', max_length=100),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference to order/transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Account wallet balance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked',
            field=models.BooleanField(default=False, help_text='Account blocked flag prevents login'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_purchase',
            field=models.DateTimeField(blank=True, help_text='Last order date', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Loyalty program points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, help_text='Redeemable points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lifetime spending total', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='warning',
            field=models.BooleanField(default=False, help_text='Account warning flag for violations'),
        ),
    ]
