# Generated by Django 5.2.7 on 2026-01-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-expires_at']},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique coupon code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Type of discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(help_text='Total redemptions allowed'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order total to apply coupon', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Discount value (% or amount)', max_digits=10),
        ),
    ]
