# Generated by Django 6.0 on 2026-01-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
