# Generated by Django 5.2.7 on 2026-01-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_status'),
        ('shop', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories that will have this discount applied', related_name='events', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('live', 'Live'), ('soon', 'Soon'), ('end', 'End'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'event_date'], name='events_even_is_acti_888d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='events_even_status_fcd052_idx'),
        ),
    ]
