# Generated by Django 5.2.7 on 2026-01-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_category_ref_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy category field (deprecated, use category_ref)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Primary category assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Product image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Legacy product ID for data migration', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional subcategory assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
