# Generated by Django 6.0 on 2026-01-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftredemption',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
