# Generated by Django 6.0 on 2026-01-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_alter_giftredemption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='points_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gift.gift'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
