# Generated by Django 5.2.7 on 2026-01-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_alter_gift_points_cost_alter_giftredemption_gift_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['points_cost', 'name'], 'verbose_name_plural': 'Gifts'},
        ),
        migrations.AlterModelOptions(
            name='giftredemption',
            options={'ordering': ['-redeemed_at'], 'verbose_name_plural': 'Gift Redemptions'},
        ),
        migrations.AlterField(
            model_name='gift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='points_cost',
            field=models.IntegerField(help_text='Loyalty points required to redeem'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='gift.gift'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes on redemption'),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('shipped', 'Shipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='giftredemption',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipment tracking number', max_length=100, null=True),
        ),
    ]
