# Generated by Django 5.2.7 on 2026-01-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_expand_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at'], 'verbose_name_plural': 'Search Histories'},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city_name',
            field=models.CharField(db_index=True, help_text='City name searched', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='description',
            field=models.CharField(blank=True, help_text='Weather description', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='feels_like',
            field=models.FloatField(blank=True, help_text='Feels-like temperature', null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='humidity',
            field=models.IntegerField(blank=True, help_text='Humidity percentage', null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='icon',
            field=models.CharField(blank=True, help_text='Weather icon code', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Current temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='wind_speed',
            field=models.FloatField(blank=True, help_text='Wind speed in km/h', null=True),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['city_name', '-searched_at'], name='weather_sea_city_na_37d28d_idx'),
        ),
    ]
